import { Injectable } from '@angular/core';
import * as uuid from 'uuid';
import * as moment from 'moment';

export class Task {
  constructor(title: string, completed: boolean, detailText?: string, dueMoment?: moment.Moment) {
    this.title = title;
    this.completed = completed;
    this.detailText = detailText;

    this.dueMoment = dueMoment;
    this.createMoment = moment();
    this.taskId = uuid.v4(); //normally this would be generated by the server, but we'll generate it for example now
  }
  taskId: string;
  title: string;
  completed: boolean;

  detailText?: string;

  // add two moment properties for create and due dates/times
  createMoment: moment.Moment;
  dueMoment: moment.Moment;
}

@Injectable({
  providedIn: 'root'
})

export class TasksService {

  tasks: Task[] = [
    new Task('Walk the dog', false),
    new Task('Buy dog food', false)
  ]

  constructor() {
  }

  addTask(title: string, completed: boolean, detail? : string) {
    this.tasks.push(new Task(title,completed, detail));
  }

  deleteTask(i: number) {
    console.log(i);
    this.tasks.splice(i, 1);
  }

  getTasks(): Task[] {
    return this.tasks;
  }

}


